/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 855ae762655f5d7f23dd9da4d8335444)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database";
	}
	interface Env {
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		R2: R2Bucket;
		INGESTION_QUEUE: Queue;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
