/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: b726ab77fd3cba0590b9aa34f49e9b10)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database";
	}
	interface Env {
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		R2: R2Bucket;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
